# Generated by Django 4.2 on 2025-01-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=15, verbose_name="номер телефона"),
        ),
    ]
