# Generated by Django 4.2 on 2025-01-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_invite_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="invite_code",
            field=models.CharField(
                blank="True",
                max_length=6,
                null="True",
                unique=True,
                verbose_name="инвайт-код",
            ),
        ),
    ]
