# Generated by Django 4.2 on 2025-01-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_invite_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activated_invite_code",
            field=models.CharField(
                blank="True",
                max_length=6,
                null="True",
                verbose_name="активированный инвайт-код",
            ),
            preserve_default="True",
        ),
    ]
