# Generated by Django 4.2 on 2025-01-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_activated_invite_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=15, unique=True, verbose_name="номер телефона"
            ),
        ),
    ]
